// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgAlhYfa4e3ihTDpZ5UGeZgkcro-HjHE',
    appId: '1:499482163771:web:085097caf7e956926a3a1e',
    messagingSenderId: '499482163771',
    projectId: 'ceylon-luxury-bedding',
    authDomain: 'ceylon-luxury-bedding.firebaseapp.com',
    storageBucket: 'ceylon-luxury-bedding.firebasestorage.app',
    measurementId: 'G-BF06B11EV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm3W6oEi7DwaQSEtjig8ZrQJJG9c4VGFM',
    appId: '1:499482163771:android:c2cf30bb99ef726f6a3a1e',
    messagingSenderId: '499482163771',
    projectId: 'ceylon-luxury-bedding',
    storageBucket: 'ceylon-luxury-bedding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJtuNp9LxKAOv8SW2Eiuqa87KMy6-Yu7Q',
    appId: '1:499482163771:ios:fdbec6f3190d583b6a3a1e',
    messagingSenderId: '499482163771',
    projectId: 'ceylon-luxury-bedding',
    storageBucket: 'ceylon-luxury-bedding.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJtuNp9LxKAOv8SW2Eiuqa87KMy6-Yu7Q',
    appId: '1:499482163771:ios:fdbec6f3190d583b6a3a1e',
    messagingSenderId: '499482163771',
    projectId: 'ceylon-luxury-bedding',
    storageBucket: 'ceylon-luxury-bedding.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWgAlhYfa4e3ihTDpZ5UGeZgkcro-HjHE',
    appId: '1:499482163771:web:aca39c31a838207b6a3a1e',
    messagingSenderId: '499482163771',
    projectId: 'ceylon-luxury-bedding',
    authDomain: 'ceylon-luxury-bedding.firebaseapp.com',
    storageBucket: 'ceylon-luxury-bedding.firebasestorage.app',
    measurementId: 'G-MEQ7HYJHDF',
  );

}